### ISSUE TITLE
Error: No emulators found

### ISSUE THREAD

**Issue by Majoramari** [TcNobo/TcNo-WSA-SimpleSideload#6]
I get this error when installing apk 

`adb.exe: no devices/emulators found`

EDIT: after restart it gives me this error:

`adb.exe: more than one device/emulator`

NOTE: I tried to install it manually using `adb install` but it also fail so it's not an issue with SimpleSideload, feel free to close this issue...

**Comment by TcNobo** [comment]
Mostly USB debugging not setup properly, or the connection between PC-Phone is weird for some reason or another [https://stackoverflow.com/questions/10705089/how-to-fix-error-device-not-found-with-adb-exe](https://stackoverflow.com/questions/10705089/how-to-fix-error-device-not-found-with-adb-exe)
